{'accuracy': 0.9786474105132386, 'precision': 0.9818181818181818, 'recall': 0.16463414634146342, 'f1': 0.2819843342036554, 'roc_auc': np.float64(0.5746001436091964)}
Traceback (most recent call last):
  File "/mnt/d/DETECT/MODELS/RFC.py", line 123, in <module>
    prob_true, prob_pred, counts = calibration_curve(
  File "/home/jorge/miniconda3/envs/detect/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/jorge/miniconda3/envs/detect/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/jorge/miniconda3/envs/detect/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'return_counts'
